---

name: pySDC_monodomain
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy>=0.17.1
  - matplotlib>=3.0
  - sympy>=1.0
  - numba>=0.35
  - dill>=0.2.6
  - pytest
  - pytest-benchmark
  - pytest-timeout
  - pytest-order
  - coverage[toml]
  - sphinx
  - numdifftools
  - pybind11
  - mpi4py
  - mpich
  - tqdm
  - pymp-pypi
  - pip
  - pip:
    - qmat>=0.1.8
